### PR TITLE
Bug fixed: Cannot read property '0' of undefined at ResizeHandler._ex…

### PR DESCRIPTION
**Pull request by bsekachev**
…tractPosition

Case is possible when event.clientX or event.clientY or both is 0. Then first condition equivalent to false. Property "touches" is undefined for mouse event and exception occurred.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Thanks for the PR!

I think it would be nicer to have:

```js
return {
  x: event.clientX != null ? event.clientX : event.touches[0].pageX,
  y: event.clientY != null ? event.clientY : event.touches[0].pageY
 }
```

What do you think?

**Comment by bsekachev** [comment]
Thanks, yes, it looks better.
I don't sure what "clientX/Y" properties of touch events is null, but in my case it work well :)

**Comment by Fuzzyma** [comment]
well if both is null then something is wrong anyway :D. 
I just looked again at teh code and iam wondering why we use the pageX/pageY coordinates from the touches but the clientX/clientY in the other case. It should always be clientX/clientY imo.
Maybe you can change that, too while you are on it :)

**Comment by bsekachev** [comment]
Yes, I will do it :)

**Comment by bsekachev** [comment]
Do you need minified js version?

**Comment by Fuzzyma** [comment]
Wont hurt when you run gulp once :)

**Comment by bsekachev** [comment]
Already done :)

**Comment by Fuzzyma** [comment]
Awesome! :)

**Pull request merged**
